replicaCount: 2

image:
  repository: nickvab/wordpress
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

service:
  type: ClusterIP
  port: 80

ingress:
  hostname: wordpress.k8s-3.sa

persistentVolumeClaim:
  storageSize: 8Gi

env:
  - name: WORDPRESS_DB_HOST
    value: 192.168.203.3
  - name: WORDPRESS_DB_NAME
    value: bitnami_wordpress
  - name: WORDPRESS_DB_USER
    value: admin
  - name: WORDPRESS_DB_PASSWORD
    value: wordpress
    #  - name: WP_DEBUG_LOG
    #    value: wordpress
