replicaCount: 2

image:
  repository: nickvab/wordpress
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  type: ClusterIP
  port: 80

ingress:
  hostname: wordpress.k8s-23.sa

persistentVolumeClaim:
  storageSize: 8Gi

env:
  - name: WORDPRESS_DB_HOST
    value: 192.168.203.23
  - name: WORDPRESS_DB_NAME
    value: wordpress
  - name: WORDPRESS_DB_USER
    value: wordpress
  - name: WORDPRESS_DB_PASSWORD
    value: wordpress
