name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out the repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
          
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./Docker
          push: true
          tags: agbusko/wordpress:${{ steps.tag_version.outputs.new_tag }}
          
      - name: Helm tool
        uses: Azure/setup-helm@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Test manifests
        continue-on-error: true
        uses: instrumenta/kubeval-action@master
        with: 
          files: ./wordpress/templates
          
      - name: Publish Helm charts
        uses: stefanprodan/helm-gh-pages@master
        with:
          charts_dir: ./Helm
          branch: main
          linting: off
          charts_url: https://agbusko.github.io/wordpress/
          token: ${{ secrets.GITHUB_TOKEN }}
          app_version: ${{ steps.tag_version.outputs.new_tag }}
          chart_version: ${{ steps.tag_version.outputs.new_tag }}
          
      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: nickvab
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/43742164?s=32&v=4
          SLACK_MESSAGE: 'A new version of the project has been released'
          SLACK_TITLE: 'Good job!'
          SLACK_USERNAME: agent
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
